# Generated by Django 3.0.4 on 2020-03-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_key_index', models.IntegerField(default=-1)),
                ('has_changed_count', models.IntegerField(default=0)),
                ('current_song', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songview.Song')),
            ],
        ),
    ]
