# Generated by Django 3.0.4 on 2020-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0004_auto_20200407_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
