# Generated by Django 2.2.12 on 2020-09-06 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0005_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_beaming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='owner',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
