# Generated by Django 2.2.12 on 2020-10-04 16:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0006_auto_20200906_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='owner',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='set',
            name='song_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
