# Generated by Django 2.2.12 on 2020-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0006_auto_20200906_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='owner',
            field=models.CharField(default='', max_length=36),
        ),
    ]
