# Generated by Django 2.2.12 on 2020-10-04 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0007_auto_20201004_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='song_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
