# Generated by Django 2.2.12 on 2020-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0007_auto_20201004_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
