# Generated by Django 2.2.12 on 2020-11-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0008_set_is_protected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='beamed_song_index',
        ),
        migrations.RemoveField(
            model_name='set',
            name='has_changed_count',
        ),
        migrations.RemoveField(
            model_name='set',
            name='is_beaming',
        ),
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(default='', max_length=36)),
                ('current_song_index', models.IntegerField(default=None, null=True)),
                ('has_changed_count', models.IntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechorder.Set')),
            ],
        ),
    ]
