# Generated by Django 2.2.12 on 2020-11-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0009_added_beam_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='beam',
            name='beamer_device_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
