# Generated by Django 2.2.12 on 2020-11-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0010_beam_beamer_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='key_notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
