# Generated by Django 2.2.12 on 2020-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0011_song_key_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='verse_order',
            field=models.CharField(default='', max_length=200),
        ),
    ]
