# Generated by Django 4.0.6 on 2023-11-05 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def set_created_at(apps, schema_editor):
    sets = apps.get_model('rechorder', 'Set')
    for set in sets.objects.all():
        set.created_at = set.last_updated
        set.save()


class Migration(migrations.Migration):
    dependencies = [
        ('rechorder', '0015_song_ccli_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='song_list',
        ),
        migrations.AddField(
            model_name='set',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_set', models.IntegerField()),
                ('sounding_key_index', models.IntegerField()),
                ('notes', models.TextField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechorder.set')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechorder.song')),
            ],
        ),
        migrations.RunPython(set_created_at, migrations.RunPython.noop),
    ]
