# Generated by Django 4.0.6 on 2023-11-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechorder', '0016_remove_set_song_list_set_created_at_iteminset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beam',
            name='current_song_index',
        ),
        migrations.RemoveField(
            model_name='beam',
            name='set',
        ),
        migrations.AddField(
            model_name='beam',
            name='current_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rechorder.iteminset'),
        ),
        migrations.AlterField(
            model_name='iteminset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rechorder.set'),
        ),
    ]
